stages:
  pull_shelly_data:
    cmd: python export_history.py --date-from ${date_from} --date-to ${date_to} --output ${live_db}
    deps:
      - export_history.py
      - params.yaml
    params:
      - date_from
      - date_to
      - live_db
  snapshot_shelly_db:
    cmd: cp ${live_db} ${output_db}
    deps:
      - ${live_db}
      - params.yaml
    params:
      - output_db
    outs:
      - ${output_db}
